version: "3"
services:
  gateway:
    container_name: learn-nestjs_gateway
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - db
    links:
      - "order:order"
  order:
    container_name: learn-nestjs_order
    build: ./order-service
    restart: always
    hostname: order
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - backend
    depends_on:
      - db
  payment:
    container_name: learn-nestjs_payment
    build: ./payment-service
    restart: always
    hostname: payment
    env_file:
      - .env
    ports:
      - "3002:3002"
    networks:
      - backend
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    restart: always
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - ./db/data/db-files:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
  mongo-express:
    container_name: db_admin
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpw
      ME_CONFIG_MONGODB_SERVER: db
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - db
networks:
  backend:
    driver: bridge
