apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: order
    spec:
      containers:
        - env:
            - name: API_GATEWAY_PORT
              valueFrom:
                configMapKeyRef:
                  key: API_GATEWAY_PORT
                  name: env
            - name: BASE_URI
              valueFrom:
                configMapKeyRef:
                  key: BASE_URI
                  name: env
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_DATABASE
                  name: env
            - name: MONGO_DSN
              valueFrom:
                configMapKeyRef:
                  key: MONGO_DSN
                  name: env
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  key: MONGO_HOST
                  name: env
            - name: MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_PASSWORD
                  name: env
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_ROOT_PASSWORD
                  name: env
            - name: MONGO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  key: MONGO_ROOT_USER
                  name: env
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI
                  name: env
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  key: MONGO_USER
                  name: env
            - name: ORDER_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: ORDER_SERVICE_HOST
                  name: env
            - name: ORDER_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: ORDER_SERVICE_PORT
                  name: env
            - name: PAYMENT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: PAYMENT_SERVICE_HOST
                  name: env
            - name: PAYMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: PAYMENT_SERVICE_PORT
                  name: env
          image: localhost:5000/learn-nestjs_order
          name: learn-nestjs-order
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          resources: {}
      hostname: order
      restartPolicy: Always
status: {}
